# Linear Algebra

In [1]:
import numpy as np

In [2]:
A = np.random.rand(9)
A

array([0.08199801, 0.06931615, 0.80205262, 0.61714807, 0.48672784,
       0.68703431, 0.75754813, 0.0382409 , 0.08556323])

In [3]:
A.ndim

1

In [4]:
A.size

9

In [5]:
A.itemsize

8

In [6]:
A.dtype

dtype('float64')

In [7]:
A.nbytes

72

In [8]:
B = A.reshape(3,3)

In [9]:
B

array([[0.08199801, 0.06931615, 0.80205262],
       [0.61714807, 0.48672784, 0.68703431],
       [0.75754813, 0.0382409 , 0.08556323]])

In [10]:
np.linalg.matrix_rank(B)

3

In [11]:
np.linalg.det(B)

-0.24312726354460595

In [12]:
Binv = np.linalg.inv(B)
Binv

array([[-0.06323107, -0.10175865,  1.40979158],
       [-1.92350446,  2.47021843, -1.80419822],
       [ 1.41950131, -0.20308146,  0.01179469]])

In [13]:
np.dot(B,Binv)

array([[ 1.00000000e+00, -2.48449010e-17, -2.87182865e-19],
       [-1.25643519e-17,  1.00000000e+00,  2.58501718e-17],
       [-4.29082066e-18, -1.09832440e-17,  1.00000000e+00]])

In [14]:
B.dtype

dtype('float64')

In [15]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

## Solving a linear set of equations

In [16]:
P = np.mat('1, -2, 1; 0, 1, -4; -4, 5, 9')
P

matrix([[ 1, -2,  1],
        [ 0,  1, -4],
        [-4,  5,  9]])

In [17]:
Q = np.mat('1,4,-13').transpose()
Q

matrix([[  1],
        [  4],
        [-13]])

In [18]:
X = np.linalg.solve(P,Q)

In [19]:
X

matrix([[30.],
        [16.],
        [ 3.]])

In [20]:
np.dot(P,X)

matrix([[  1.],
        [  4.],
        [-13.]])

In [21]:
np.linalg.eig(B)

EigResult(eigenvalues=array([-0.6950547 ,  0.99930444,  0.35003935]), eigenvectors=array([[-0.71652977,  0.3561331 ,  0.09031647],
       [-0.03094354,  0.87353773, -0.98917297],
       [ 0.69686985,  0.33181478,  0.11567097]]))

In [22]:
B.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [23]:
C = np.random.rand(10000,10000)

In [24]:
F = np.asfortranarray(C)

In [25]:
F.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [26]:
def sum_row(x):
    return np.sum(x[0,:])

def sum_col(x):
    return np.sum(x[:,0])

In [27]:
C.strides

(80000, 8)

In [28]:
F.strides

(8, 80000)

In [29]:
%timeit sum_row(C)

6.76 µs ± 69.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [30]:
%timeit sum_col(C)

19.6 µs ± 241 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [31]:
%timeit sum_row(F)

20.7 µs ± 746 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [32]:
%timeit sum_col(F)

6.83 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [33]:
X = np.array([1,2,3])

In [34]:
X

array([1, 2, 3])

In [35]:
Y = np.random.rand(3)
Y

array([0.94242485, 0.59305762, 0.50417583])

In [36]:
X + 1

array([2, 3, 4])

In [37]:
Y * 2 

array([1.8848497 , 1.18611523, 1.00835166])

In [38]:
Y / X

array([0.94242485, 0.29652881, 0.16805861])

In [39]:
X * Y

array([0.94242485, 1.18611523, 1.5125275 ])

In [40]:
X ** 2

array([1, 4, 9])

In [41]:
np.dot(X,Y)

3.6410675814847506

In [42]:
np.inner(X,Y)

3.6410675814847506

In [43]:
np.outer(X,Y)

array([[0.94242485, 0.59305762, 0.50417583],
       [1.8848497 , 1.18611523, 1.00835166],
       [2.82727455, 1.77917285, 1.5125275 ]])

In [44]:
np.cross(X,Y)

array([-0.77082119,  2.32309872, -1.29179209])

In [45]:
M = np.random.rand(5,5)

In [46]:
M

array([[0.45677632, 0.36247527, 0.31785361, 0.23527022, 0.17109726],
       [0.66226546, 0.55615277, 0.35695639, 0.04141433, 0.82869199],
       [0.72825251, 0.68889971, 0.04642523, 0.18640724, 0.32109396],
       [0.60911344, 0.84213441, 0.75047589, 0.9006482 , 0.17705345],
       [0.24743859, 0.22223695, 0.29569843, 0.52005332, 0.07424867]])

In [47]:
mask = (M < 0.5)

In [48]:
mask

array([[ True,  True,  True,  True,  True],
       [False, False,  True,  True, False],
       [False, False,  True,  True,  True],
       [False, False, False, False,  True],
       [ True,  True,  True, False,  True]])

In [49]:
M [mask] = 0

In [50]:
M

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.66226546, 0.55615277, 0.        , 0.        , 0.82869199],
       [0.72825251, 0.68889971, 0.        , 0.        , 0.        ],
       [0.60911344, 0.84213441, 0.75047589, 0.9006482 , 0.        ],
       [0.        , 0.        , 0.        , 0.52005332, 0.        ]])

In [51]:
V1 = np.linspace(1,3,num=3)
V1

array([1., 2., 3.])

In [52]:
V2 = V1**2

In [53]:
V2

array([1., 4., 9.])

In [54]:
VCS = np.column_stack((V1,V2))

In [55]:
VCS

array([[1., 1.],
       [2., 4.],
       [3., 9.]])

In [56]:
VRS = np.row_stack((V1,V2))

In [57]:
VRS

array([[1., 2., 3.],
       [1., 4., 9.]])

In [58]:
VCS.shape

(3, 2)

In [59]:
VRS.shape

(2, 3)

In [60]:
Q1 = np.linspace(1,9,num=9).reshape(3,3)
Q1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [61]:
Q2 = Q1 ** 2

In [62]:
Q2

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [63]:
QH = np.hstack((Q1,Q2))

In [64]:
QH

array([[ 1.,  2.,  3.,  1.,  4.,  9.],
       [ 4.,  5.,  6., 16., 25., 36.],
       [ 7.,  8.,  9., 49., 64., 81.]])

In [65]:
QH.shape

(3, 6)

In [66]:
QV = np.vstack((Q1,Q2))

In [67]:
QV

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [68]:
QV.shape

(6, 3)

In [69]:
QC1 = np.concatenate((Q1,Q2), axis=1)

In [70]:
QC1

array([[ 1.,  2.,  3.,  1.,  4.,  9.],
       [ 4.,  5.,  6., 16., 25., 36.],
       [ 7.,  8.,  9., 49., 64., 81.]])

In [71]:
QC2 = np.concatenate((Q1,Q2), axis=0)

In [72]:
QC2

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [73]:
QD = np.dstack((Q1,Q2))

In [74]:
QD

array([[[ 1.,  1.],
        [ 2.,  4.],
        [ 3.,  9.]],

       [[ 4., 16.],
        [ 5., 25.],
        [ 6., 36.]],

       [[ 7., 49.],
        [ 8., 64.],
        [ 9., 81.]]])

In [75]:
QD.shape

(3, 3, 2)